### ISSUE TITLE
Kernel crash using minicom

### ISSUE THREAD

**Issue by wigcheng** [brendanhoran/xr_usb_serial_common#1]
Kernel: 5.4.70
Platform: ARMv8 IMX8MP SOC
OS: Linux

That is crash log using minicom tool:

root@imx8mp:~# modprobe xr_usb_serial_common
[   84.221527] cdc_xr_usb_serial 1-1.6:1.0: This device cannot do calls on its own. It is not a modem.
[   84.230688] cdc_xr_usb_serial 1-1.6:1.0: ttyXR_USB_SERIAL0: USB XR_USB_SERIAL device
[   84.239467] cdc_xr_usb_serial 1-1.6:1.2: This device cannot do calls on its own. It is not a modem.
[   84.248676] cdc_xr_usb_serial 1-1.6:1.2: ttyXR_USB_SERIAL1: USB XR_USB_SERIAL device
[   84.257375] usbcore: registered new interface driver cdc_xr_usb_serial
[   84.263962] xr_usb_serial_common: Exar USB UART (serial port) driver
root@edm-g-imx8mp:~# [   94.486511] ------------[ cut here ]------------
[   94.491321] transfer buffer not dma capable
[   94.495753] WARNING: CPU: 0 PID: 722 at drivers/usb/core/hcd.c:1492 usb_hcd_map_urb_for_dma+0x4e0/0x500
[   94.505150] Modules linked in: xr_usb_serial_common(O) crct10dif_ce imx_sdma flexcan can_dev [last unloaded: cdc_acm]
[   94.515770] CPU: 0 PID: 722 Comm: minicom Tainted: G           O      5.4.70-00586-g0565c78324e6-dirty #45
[   94.525421] Hardware name: TechNexion TEK3-IMX8MP box PC (DT)
[   94.531169] pstate: 40000005 (nZcv daif -PAN -UAO)
[   94.535965] pc : usb_hcd_map_urb_for_dma+0x4e0/0x500
[   94.540932] lr : usb_hcd_map_urb_for_dma+0x4e0/0x500
[   94.545895] sp : ffff800011c4b9e0
[   94.549211] x29: ffff800011c4b9e0 x28: 00000000000000c0 
[   94.554524] x27: 0000000000000001 x26: 0000000080000380 
[   94.559834] x25: ffff800011c4bcb6 x24: 0000000000000c00 
[   94.565147] x23: 0000000000000002 x22: 0000000000000001 
[   94.570459] x21: 00000000fffffff5 x20: ffff0000f9572000 
[   94.575773] x19: ffff0000f9679f00 x18: ffffffffffffffff 
[   94.581086] x17: 0000000000000000 x16: 0000000000000000 
[   94.586398] x15: ffff8000114e88c8 x14: 0000000000000000 
[   94.591710] x13: 0000000000000001 x12: 0000000000000000 
[   94.597022] x11: 0000000000000000 x10: 00000000000009c0 
[   94.602333] x9 : ffff800011c4b6c0 x8 : ffff0000f3d18a20 
[   94.607643] x7 : ffff0000f9b069c0 x6 : ffff0000f80a7000 
[   94.612956] x5 : 0000000000000000 x4 : 0000000000000000 
[   94.618267] x3 : 0000000000000000 x2 : ffff0000ff763ce0 
[   94.623580] x1 : 713b8486ae55b800 x0 : 0000000000000000 
[   94.628894] Call trace:
[   94.631344]  usb_hcd_map_urb_for_dma+0x4e0/0x500
[   94.635963]  xhci_map_urb_for_dma+0x58/0x68
[   94.640147]  usb_hcd_submit_urb+0xa0/0x900
[   94.644243]  usb_submit_urb+0x2d8/0x4b8
[   94.648080]  usb_start_wait_urb+0x68/0x100
[   94.652177]  usb_control_msg+0xb8/0x130
[   94.656018]  xr_usb_serial_get_reg+0x118/0x1f8 [xr_usb_serial_common]
[   94.662461]  xr_usb_serial_tty_tiocmget+0x34/0xc0 [xr_usb_serial_common]
[   94.669164]  tty_ioctl+0x30c/0xd28
[   94.672567]  do_vfs_ioctl+0xbc/0xa10
[   94.676142]  ksys_ioctl+0x84/0x98
[   94.679459]  __arm64_sys_ioctl+0x18/0xa0
[   94.683384]  el0_svc_common.constprop.3+0x60/0x170
[   94.688176]  el0_svc_handler+0x6c/0x88
[   94.691928]  el0_svc+0x8/0x208
[   94.694982] ---[ end trace 8245bfcf95c7221c ]---
[   94.699688] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[   94.709406] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[   94.731767] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[   95.740295] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[   96.750070] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[   97.759857] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[   97.966041] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[   98.774083] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[   99.077750] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[   99.349871] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11
[  100.359694] cdc_xr_usb_serial 1-1.6:1.0: xr_usb_serial_get_reg channel:0 Reg 0x1f Error:-11

But use microcom has no problem, do you know how to fix it? Because I want to test hardware flow control, thanks a lot.

**Comment by brendanhoran** [comment]
Hi,

Thanks for the report.
Might need some more information as I don't have any ARM devices.
I can see that the device supports H/W flow control from reading the vendor's documents.
Also, I am just building what they provide, with some small fixes so not sure I can resolve this for you.

However, if it works in Microcom and not minicom I am wondering if this is an issue with Minicom?

Is there any other way you can test H/W flow control?

**Comment by wigcheng** [comment]
I just tried stty to setting H/W flow control first, then test flow control using microcom, it has no any response (might be my cable/ hardware issue), at least I have a way to try.

In addition, I found latest kernel upstream has a CONFIG_SERIAL_XR driver can running XR series, I build-in and try, minicom has no crash issue but still no any response if I enable flow control.

The RTS always low using scope measuring.
That is my progress(try these two drivers), I'll keep update status here, thanks.

**Comment by brendanhoran** [comment]
If both this driver and the in-kernel driver do not work with H/W flow control, I would assume there is a bug with the vendor's provided code.
I build from:
https://www.maxlinear.com/support/design-tools/software-drivers

As you can see they don't update it much. It might be worth asking them for help or filing a bug there if possible?

I don't think I will be able to help much sadly :(

**Comment by wigcheng** [comment]
No, thanks for your response, I already solve it last month ( HW issue...) so the driver has no problems, thanks!

**Comment by brendanhoran** [comment]
Thanks for the feedback, glad your issue is solved. 
I will close this issue now.
